name: utils
channels:
- conda-forge
dependencies:
- python<3.12
- netcdf4
- cartopy
- eofs
- matplotlib
- numpy
- scikit-learn
- scipy
- xarray
- dask
- cfgrib
- xesmf>0.8
- cdo
- cdsapi
- python-cdo
